#

[install]
linker = "isolated"
publicHoistPattern = [ "drizzle-orm", "pg" ]

[test]

[build]
clientScripts = [
  "sources/web/src/**/*.client.ts",
  "sources/web/src/**/*.client.tsx"
]
external = ["preact", "preact/jsx-dev-runtime", "preact/jsx-runtime", "@preact/signals"]
