#

[install]
linker = "isolated"
publicHoistPattern = [ "drizzle-orm", "pg" ]

[test]
preload = ["@~/config.bun-plugin-test-projects"]

[test."*.test.dom.tsx"]
preload = ["@~/config.happydom/register.ts"]
