#

[install]
linker = "isolated"
publicHoistPattern = [ "drizzle-orm", "pg" ]

[test]

[build]
clientScripts = [
  "sources/web/src/**/*.client.ts",
  "sources/web/src/**/*.client.tsx"
]
external = ["@preact/signals", "preact"]
