#

include:
  - path: ./mocks/docker-compose.mocks.yaml

services:
  postgres-identite-proconnect:
    image: postgres:16.11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  postgres-hyyyperbase:
    image: postgres:16.11-alpine
    volumes:
      - postgres-hyyyperbase:/var/lib/postgresql/data
      - ./mocks/postgres-hyyyperbase/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_DB: hyyyperbase
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hyyyperbase"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "5555:5432"

volumes:
  postgres:
  postgres-hyyyperbase:
