#

name: ðŸ‘· CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TZ: Europe/Paris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
      - run: bun install --frozen-lockfile
      - run: bun run format
      - run: bun run build
      - run: bun run test:type-check
      - run: bun test
          --coverage
          --coverage-reporter=lcov
          --coverage-reporter=text
